tap 'homebrew/dupes'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'mas'
brew 'git'
brew 'python'
brew 'gcc'
brew 'gdb'
brew 'tmux'
brew 'bash-completion'
brew 'tig'
brew 'mtr'
brew 'nmap'
brew 'shellcheck'
brew 'wget'
brew 'htop'
brew 'make'
brew 'node'

cask 'atom'
cask 'brackets'
cask 'firefox'
cask 'gimp'
cask 'google-chrome'
cask 'java'
cask 'iterm2'
cask 'slack'
cask 'spectacle'
cask 'the-unarchiver'
cask 'little-snitch'
cask 'vagrant'
cask 'visual-studio-code'
cask 'flux'
cask 'caffeine'
cask 'sourcetree'

#mas 'Alfred', id: 405843582
#mas 'Evernote', id: 406056744